DROP TABLE IF EXISTS Boxes;
CREATE TABLE Boxes (
  ID         INTEGER PRIMARY KEY,
  INDOOR     BOOLEAN,
  WINDOWS    BOOLEAN,
  DAILY_RATE DECIMAL,
  AREA       DOUBLE,
  PHOTO      BLOB,
  NAME       VARCHAR(128)
);

DROP TABLE IF EXISTS Bookings;
CREATE TABLE Bookings (
  ID            INTEGER PRIMARY KEY,
  BEGIN_TIME    DATE,
  END_TIME      DATE,
  CUSTOMER_NAME VARCHAR(128)
);

DROP TABLE IF EXISTS BoxBookings;
CREATE TABLE BoxBookings (
  BOOKING_ID INTEGER,
  BOX_ID     INTEGER,
  HORSE_NAME VARCHAR(128),
  DAILY_RATE DECIMAL,
  PRIMARY KEY (BOOKING_ID, BOX_ID),
  FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS (ID) ON DELETE CASCADE,
  FOREIGN KEY (BOX_ID) REFERENCES BOXES (ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS BoxImages;
CREATE TABLE BoxImages (
  BOX_ID    INTEGER,
  FILE_PATH VARCHAR(128),
  PRIMARY KEY (BOX_ID),
  FOREIGN KEY (BOX_ID) REFERENCES BOXES (ID) ON DELETE CASCADE
);
