DROP TABLE IF EXISTS Boxes;
CREATE TABLE Boxes (
	ID INTEGER PRIMARY KEY,
	INDOOR BOOLEAN,
	WINDOWS BOOLEAN,
	DAILY_RATE DECIMAL,
	AREA DOUBLE,
	PHOTO BLOB,
	NAME VARCHAR(128)
);

DROP TABLE IF EXISTS Reservations;
CREATE TABLE Reservations (
	ID INTEGER PRIMARY KEY,
	BEGIN_TIME DATE,
	END_TIME DATE,
	CUSTOMER_NAME VARCHAR(128)
);

DROP TABLE IF EXISTS BoxReservations;
CREATE TABLE BoxReservations (
	RESERVATION_ID INTEGER ,
	BOX_ID INTEGER,
	PRIMARY KEY(RESERVATION_ID, BOX_ID),
	FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(ID),
	FOREIGN KEY (BOX_ID) REFERENCES BOXES(ID)
); 
